name: .NET Core

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: Nuget pack
        run:  dotnet pack -c Release -o out
      - name: Push nuget
        run: dotnet nuget push .\out\*.nupkg --skip-duplicate --no-symbols true
