name: .NET Core

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: Setup Github nuget
        run: dotnet nuget add source https://nuget.pkg.github.com/redbaty/index.json -n github -u redbaty -p GH_TOKEN --store-password-in-clear-text
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Nuget pack
        run:  dotnet pack -c Release -o out -p:PackageVersion=1.0.${{ github.run_number }}
      - name: Push nuget
        run: dotnet nuget push ./out/*.nupkg --skip-duplicate --no-symbols true --source "github"
