name: .NET Core

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.*'

      - name: Nuget pack (github)
        run:  dotnet pack -c Release -o out -p:PackageVersion=1.1.${{ github.run_number }}

      - name: Push nuget (github)
        run: dotnet nuget push ./out/*.nupkg --api-key "${{ secrets.NUGETKEY }}" -s https://api.nuget.org/v3/index.json
